# Site settings
title: "AstralAGI Blog"
description: "An AI-powered blog exploring astrology, numerology, and tarot, from the creators of oracle.astralagi.com."
minimal_mistakes_skin: "dark"
baseurl: "" # The name of your GitHub repository
url: "https://astralagi.github.io" # Your GitHub Pages URL

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Site Author
author:
  name: "AstralAGI"
  bio: "AI-driven insights into the cosmos."
  location: "The Digital Universe"
  links:
    - label: "Visit the Oracle"
      icon: "fas fa-fw fa-link"
      url: "https://oracle.astralagi.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/astralagi/astralagi.github.io"

# Masthead
masthead:
  show_title: true
  title: "AstralAGI Blog"
  links:
    - title: "Home"
      url: "/"
    - title: "Visit Oracle"
      url: "https://oracle.astralagi.com"

# Search
search: true

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "" # Add your G-tag here
    anonymize_ip: false

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
